version: '2'

services:
  rails:
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    env_file:
      - app.env
    depends_on:
      - mysql
    working_dir: /app
      
  mysql:
    image: mysql:5.7.16
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
