version: '2'

services:
  nginx:
    image: nginx:1.11.5
    volumes:
      - ./public:/app/public
      - ./config/nginx_sites.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - app

  app:
    env_file:
      - ./app.production.env
    ports: []
