default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DEFAULT_DATABASE_USER'] %>
  password: <%= ENV['DEFAULT_DATABASE_PASSWORD'] %>
  host: <%= ENV['DEFAULT_DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USER'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
